package com.github.suditoli.melawi.json;

import com.github.suditoli.melawi.json.generate.JSONGenerator;
import com.github.suditoli.melawi.json.parser.JSONParser;
import com.github.suditoli.melawi.xml.generate.XMLGenerator;
import java.math.BigDecimal;
import java.math.BigInteger;
import org.junit.Assert;
import org.junit.Test;

public class TestJSON {

    @Test
    public void test() {
        Assert.assertTrue(Boolean.TRUE);
    }
    
    public static void main(String[] args) throws Exception {
        System.out.println("kok error?"); //Problem: Project Problem: Project's main artifact is processed through maven-shade-plugin, resolvable by: org.netbeans.modules.maven.problems.ProblemReporterImpl$MavenProblemResolver@3f343af1 unresolved
        JSONObject project = new JSONObject()
                .object(o
                        -> o.addString("name", "molten-json")
                        .addString("version", "0.1.0")
                        .addString("description", "A fluent Java 8 DSL for working with JSON.")
                        .addObject("repository",
                                r -> r.addString("type", "git")
                                        .addString("url", "https://github.com/helpermethod/molten-json"))
                        .addArray("keywords", k -> k.addStrings("json", "java-8", "fluent", "dsl"))
                        .addString("author", "helpermethod")
                        .addString("license", "Apache 2")
                        .addArray("bugs",
                                b -> b.addObject(no -> no.addString("url", "https://github.com/helpermethod/molten-json/issues"))
                                        .addObject(no -> no.addString("url", "https://github.com/helpermethod/melawi-json/issues")))
                        .addNull("null")
                        .addString("empty", "")
                        .addString("integerString", "12345")
                        .addObject("emptyObject", eo -> new JSONObject())
                        .put("emptyObject2", new JSONObject())
                );
        System.out.println(project.toString());
        System.out.println("empty string: " + project.isEmpty("empty"));
        System.out.println("empty object: " + project.isEmpty("emptyObject"));
        System.out.println("empty object2: " + project.isEmpty("emptyObject2"));
        System.out.println("null field: " + project.isNull("null"));
        System.out.println("object to array: " + project.getJSONArray("repository"));
        System.out.println("array to object[0]: " + project.getJSONObject("bugs"));
        System.out.println("get empty string as object: " + project.getJSONObject("empty"));
        System.out.println("get empty string as object and child object: " + project.getJSONObject("empty").getJSONObject("imposible"));
        int intString = project.getInteger("integerString");
        System.out.println("IntergerString: " + intString);

        JSONParser parser = new JSONParser();
        JSONObject reader = parser.parseAsObject(project.toJSONString());
        System.out.println(reader.getJSONObject("repository").toJSONString());
        System.out.println(reader.getJSONArray("keywords").toJSONString());

        String array = new JSONArray()
                .addObject(o -> o.addString("object1", "satu"))
                .addObject(o -> o.addString("object2", "satu").addNumber("angka", 123))
                .toString();
        System.out.println(array);

        XMLGenerator xml = new XMLGenerator();
        xml.startElement("Request")
                .startElement("Product")
                .addField("SellerSku", "4105382173aaee4")
                .addField("Quantity", "12")
                .endElement("Product")
                .startElement("Product")
                .addField("SellerSku", "4928a374c28ff1")
                .addField("Quantity", "4")
                .endElement("Product")
                .endElement("Request");
        System.out.println(xml.toString());

        JSONGenerator json = new JSONGenerator();
        json.startObject()
                .writeString("string", "abc")
                .writeNumber("bigInteger", BigInteger.valueOf(Long.MAX_VALUE))
                .writeNumber("bigDecimal", BigDecimal.valueOf(Double.MAX_VALUE))
                .writeNull("null")
                .writeBoolean("boolean", true)
                .startArray("arrayOfObject")
                .startObject()
                .writeNumber("object1", 1)
                .writeString("string", "satu")
                .endObject()
                .startObject()
                .writeNumber("object2", 2)
                .writeString("string", "dua")
                .endObject()
                .endArray()
                .startArray("arrayOfString")
                .writeArray("satu", "dua", "tiga")
                .endArray()
                .endObject()
                .toString();
        System.out.println(json.toString());

        String jsonString = "{\n"
                + "  \"SuccessResponse\": {\n"
                + "    \"Head\": {\n"
                + "      \"RequestId\": \"\",\n"
                + "      \"RequestAction\": \"GetProducts\",\n"
                + "      \"ResponseType\": \"Products\",\n"
                + "      \"Timestamp\": \"2021-01-15T10:39:15+0700\"\n"
                + "    },\n"
                + "    \"Body\": {\n"
                + "      \"Products\": {\n"
                + "        \"Product\": [\n"
                + "          {\n"
                + "            \"SellerSku\": \"1780401101\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"Test T-Shirt\",\n"
                + "            \"Variation\": \"S\",\n"
                + "            \"ParentSku\": \"1780401101\",\n"
                + "            \"Quantity\": \"100\",\n"
                + "            \"Available\": \"100\",\n"
                + "            \"Price\": \"290000.00\",\n"
                + "            \"SalePrice\": \"145000.00\",\n"
                + "            \"SaleStartDate\": \"2020-11-10 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2020-11-30 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/3/3e0a1b73cbeb95fcde2a6b236ca3f44d.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/a/a8d75c9209e5c805221a1ef0ccf3e791.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"BLVCK EDITIONS X 17 TALENTS OF INDONESIA&lt;br /&gt;-One of our collection collaborating with ANDY YANATA to reinvented the Independence Day of Indonesia&lt;br /&gt;-Material 100% Cotton&lt;br /&gt;-Polyflex Printing\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"Kreasi Nusantara\",\n"
                + "            \"PrimaryCategory\": \"Kemeja\",\n"
                + "            \"PrimaryCategoryId\": \"31\",\n"
                + "            \"Group\": \"\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"Test-1780401101\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Pattern\": \"Garis\",\n"
                + "              \"Material\": \"100% COTTON\",\n"
                + "              \"Gender\": \"Unisex\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"Measurements\": \"S: W :50-51 L:69-70 S1: 44-45 S2: 20-21&lt;br /&gt;M: W: 51-52 L : 72-73 S1: 45-46 S2: 22-23&lt;br /&gt;L: W: 53-54 L:74-75 S1: 47-48 S2: 24-25&lt;br /&gt;XL: W: 55-56 L: 76-77 S1: 50-51 S2: 26-27&lt;br /&gt;&lt;br /&gt;Notes: W: Width (Lebar), L: Lenght (Panjang), S1:&amp;nbsp; Lebar Bahu &amp; S2: Panjang Lengan\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-CCR14854-462ENW0J1\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"CROCBAND II SANDAL PS (B, NAVY/WHITE, C8\",\n"
                + "            \"Variation\": \"38\",\n"
                + "            \"ParentSku\": \"0888-CCR14854-462ENW0J1\",\n"
                + "            \"Quantity\": \"100\",\n"
                + "            \"Available\": \"100\",\n"
                + "            \"Price\": \"459000.00\",\n"
                + "            \"SalePrice\": \"399000.00\",\n"
                + "            \"SaleStartDate\": \"2020-12-07 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2030-12-07 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"887350775778\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/9/9e6b17c16533d7b7f92a23236319b05e.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/8/81301aae6d602e700b186e3e64c12b3b.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/ef87d9761fd66520d189c7103bb071b2.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/e62be4aa9740ecbb3058872bec0b016a.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"Crocodile\",\n"
                + "            \"PrimaryCategory\": \"Sandal\",\n"
                + "            \"PrimaryCategoryId\": \"7401\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-CCR14854-462ENW0J3\",\n"
                + "              \"SubCatType\": \"Sandals &amp; Flip Flops\",\n"
                + "              \"Color\": \"Blue\",\n"
                + "              \"ColorFamily\": \"blue\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Garis\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Spring-Summer\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"Fastening\": \"Tali\",\n"
                + "              \"ToeShape\": \"Kotak\",\n"
                + "              \"Heels\": \"Wedge\",\n"
                + "              \"ShoeWidth\": \"Medium\",\n"
                + "              \"HeelHeight\": \"Pendek (0-5.5cm)\",\n"
                + "              \"Sizesystembrand\": \"EU\",\n"
                + "              \"Measurements\": \"Length: 10 cm, Width: 10 cm, Height: 10 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-CCR14854-462ENW0J2\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"CROCBAND II SANDAL PS (B, NAVY/WHITE, C8\",\n"
                + "            \"Variation\": \"39\",\n"
                + "            \"ParentSku\": \"0888-CCR14854-462ENW0J1\",\n"
                + "            \"Quantity\": \"0\",\n"
                + "            \"Available\": \"0\",\n"
                + "            \"Price\": \"459000.00\",\n"
                + "            \"SalePrice\": \"399000.00\",\n"
                + "            \"SaleStartDate\": \"2020-12-07 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2030-12-07 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"887350775785\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/9/9e6b17c16533d7b7f92a23236319b05e.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/8/81301aae6d602e700b186e3e64c12b3b.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/ef87d9761fd66520d189c7103bb071b2.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/e62be4aa9740ecbb3058872bec0b016a.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"Crocodile\",\n"
                + "            \"PrimaryCategory\": \"Sandal\",\n"
                + "            \"PrimaryCategoryId\": \"7401\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-CCR14854-462ENW0J3\",\n"
                + "              \"SubCatType\": \"Sandals &amp; Flip Flops\",\n"
                + "              \"Color\": \"Blue\",\n"
                + "              \"ColorFamily\": \"blue\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Garis\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Spring-Summer\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"Fastening\": \"Tali\",\n"
                + "              \"ToeShape\": \"Kotak\",\n"
                + "              \"Heels\": \"Wedge\",\n"
                + "              \"ShoeWidth\": \"Medium\",\n"
                + "              \"HeelHeight\": \"Pendek (0-5.5cm)\",\n"
                + "              \"Sizesystembrand\": \"EU\",\n"
                + "              \"Measurements\": \"Length: 10 cm, Width: 10 cm, Height: 10 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-CCR14854-462ENW0J3\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"CROCBAND II SANDAL PS (B, NAVY/WHITE, C8\",\n"
                + "            \"Variation\": \"40\",\n"
                + "            \"ParentSku\": \"0888-CCR14854-462ENW0J1\",\n"
                + "            \"Quantity\": \"0\",\n"
                + "            \"Available\": \"0\",\n"
                + "            \"Price\": \"459000.00\",\n"
                + "            \"SalePrice\": \"399000.00\",\n"
                + "            \"SaleStartDate\": \"2020-12-07 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2030-12-07 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"887350775792\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/9/9e6b17c16533d7b7f92a23236319b05e.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/8/81301aae6d602e700b186e3e64c12b3b.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/ef87d9761fd66520d189c7103bb071b2.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/e/e62be4aa9740ecbb3058872bec0b016a.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"Crocodile\",\n"
                + "            \"PrimaryCategory\": \"Sandal\",\n"
                + "            \"PrimaryCategoryId\": \"7401\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-CCR14854-462ENW0J3\",\n"
                + "              \"SubCatType\": \"Sandals &amp; Flip Flops\",\n"
                + "              \"Color\": \"Blue\",\n"
                + "              \"ColorFamily\": \"blue\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Garis\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Spring-Summer\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"Fastening\": \"Tali\",\n"
                + "              \"ToeShape\": \"Kotak\",\n"
                + "              \"Heels\": \"Wedge\",\n"
                + "              \"ShoeWidth\": \"Medium\",\n"
                + "              \"HeelHeight\": \"Pendek (0-5.5cm)\",\n"
                + "              \"Sizesystembrand\": \"EU\",\n"
                + "              \"Measurements\": \"Length: 10 cm, Width: 10 cm, Height: 10 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-NEWLMP19401N00000L\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"NEW COTTON POLO\",\n"
                + "            \"Variation\": \"L\",\n"
                + "            \"ParentSku\": \"0888-NEWLMP19401N00000L\",\n"
                + "            \"Quantity\": \"10\",\n"
                + "            \"Available\": \"10\",\n"
                + "            \"Price\": \"259000.00\",\n"
                + "            \"SalePrice\": \"77700.00\",\n"
                + "            \"SaleStartDate\": \"2020-10-10 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2025-10-10 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"100013605367\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/7/79c54e0fcaa412f64906d9e188f92e24.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/b/bb45ccc272063c22daef58f5ec77e29d.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/0/00e312cdd04af279321414b09202bfd3.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"New Balance\",\n"
                + "            \"PrimaryCategory\": \"Kemeja Polos\",\n"
                + "            \"PrimaryCategoryId\": \"5714\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-NEWLMP19401N0000XL\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Solid\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Autumn\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"SleeveLength\": \"Lengan Pendek\",\n"
                + "              \"Type\": \"Setelan\",\n"
                + "              \"Neck\": \"Halter Neck\",\n"
                + "              \"Length\": \"Panjang\",\n"
                + "              \"Style\": \"Basic\",\n"
                + "              \"Fitting\": \"Slim fit\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"Waist\": \"Bawah Pinggang\",\n"
                + "              \"Measurements\": \"Length: 5 cm, Width: 5 cm, Height: 5 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-NEWLMP19401N00000S\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"NEW COTTON POLO\",\n"
                + "            \"Variation\": \"S\",\n"
                + "            \"ParentSku\": \"0888-NEWLMP19401N00000L\",\n"
                + "            \"Quantity\": \"10\",\n"
                + "            \"Available\": \"10\",\n"
                + "            \"Price\": \"259000.00\",\n"
                + "            \"SalePrice\": \"77700.00\",\n"
                + "            \"SaleStartDate\": \"2020-10-10 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2025-10-10 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"100013605369\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/7/79c54e0fcaa412f64906d9e188f92e24.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/b/bb45ccc272063c22daef58f5ec77e29d.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/0/00e312cdd04af279321414b09202bfd3.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"New Balance\",\n"
                + "            \"PrimaryCategory\": \"Kemeja Polos\",\n"
                + "            \"PrimaryCategoryId\": \"5714\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-NEWLMP19401N0000XL\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Solid\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Autumn\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"SleeveLength\": \"Lengan Pendek\",\n"
                + "              \"Type\": \"Setelan\",\n"
                + "              \"Neck\": \"Halter Neck\",\n"
                + "              \"Length\": \"Panjang\",\n"
                + "              \"Style\": \"Basic\",\n"
                + "              \"Fitting\": \"Slim fit\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"Waist\": \"Bawah Pinggang\",\n"
                + "              \"Measurements\": \"Length: 5 cm, Width: 5 cm, Height: 5 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-NEWLMP19401N00000M\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"NEW COTTON POLO\",\n"
                + "            \"Variation\": \"M\",\n"
                + "            \"ParentSku\": \"0888-NEWLMP19401N00000L\",\n"
                + "            \"Quantity\": \"10\",\n"
                + "            \"Available\": \"10\",\n"
                + "            \"Price\": \"259000.00\",\n"
                + "            \"SalePrice\": \"77700.00\",\n"
                + "            \"SaleStartDate\": \"2020-10-10 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2025-10-10 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"100013605368\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/7/79c54e0fcaa412f64906d9e188f92e24.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/b/bb45ccc272063c22daef58f5ec77e29d.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/0/00e312cdd04af279321414b09202bfd3.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"New Balance\",\n"
                + "            \"PrimaryCategory\": \"Kemeja Polos\",\n"
                + "            \"PrimaryCategoryId\": \"5714\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-NEWLMP19401N0000XL\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Solid\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Autumn\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"SleeveLength\": \"Lengan Pendek\",\n"
                + "              \"Type\": \"Setelan\",\n"
                + "              \"Neck\": \"Halter Neck\",\n"
                + "              \"Length\": \"Panjang\",\n"
                + "              \"Style\": \"Basic\",\n"
                + "              \"Fitting\": \"Slim fit\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"Waist\": \"Bawah Pinggang\",\n"
                + "              \"Measurements\": \"Length: 5 cm, Width: 5 cm, Height: 5 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"0888-NEWLMP19401N0000XL\",\n"
                + "            \"ShopSku\": \"\",\n"
                + "            \"Name\": \"NEW COTTON POLO\",\n"
                + "            \"Variation\": \"XL\",\n"
                + "            \"ParentSku\": \"0888-NEWLMP19401N00000L\",\n"
                + "            \"Quantity\": \"10\",\n"
                + "            \"Available\": \"10\",\n"
                + "            \"Price\": \"259000.00\",\n"
                + "            \"SalePrice\": \"77700.00\",\n"
                + "            \"SaleStartDate\": \"2020-10-10 00:00:00\",\n"
                + "            \"SaleEndDate\": \"2025-10-10 00:00:00\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"100013605370\",\n"
                + "            \"Url\": \"\",\n"
                + "            \"MainImage\": \"\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": [\n"
                + "                \"https://sellercenter-static.zalora.co.id/7/79c54e0fcaa412f64906d9e188f92e24.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/b/bb45ccc272063c22daef58f5ec77e29d.jpeg\",\n"
                + "                \"https://sellercenter-static.zalora.co.id/0/00e312cdd04af279321414b09202bfd3.jpeg\"\n"
                + "              ]\n"
                + "            },\n"
                + "            \"Description\": \"- Solid tone chunky sneakers with velcro strap accent&lt;br /&gt;- Leather, textile and synthetic upper&lt;br /&gt;- Leather insole&lt;br /&gt;- Rubber outsole&lt;br /&gt;- Lace up fastening\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"New Balance\",\n"
                + "            \"PrimaryCategory\": \"Kemeja Polos\",\n"
                + "            \"PrimaryCategoryId\": \"5714\",\n"
                + "            \"Group\": \"Group B\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"0888-NEWLMP19401N0000XL\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Occasion\": \"Casual\",\n"
                + "              \"Pattern\": \"Solid\",\n"
                + "              \"Material\": \"Cotton\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Season\": \"Autumn\",\n"
                + "              \"Year\": \"2020\",\n"
                + "              \"SleeveLength\": \"Lengan Pendek\",\n"
                + "              \"Type\": \"Setelan\",\n"
                + "              \"Neck\": \"Halter Neck\",\n"
                + "              \"Length\": \"Panjang\",\n"
                + "              \"Style\": \"Basic\",\n"
                + "              \"Fitting\": \"Slim fit\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"Waist\": \"Bawah Pinggang\",\n"
                + "              \"Measurements\": \"Length: 5 cm, Width: 5 cm, Height: 5 cm, Weight: 3000 g\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          },\n"
                + "          {\n"
                + "            \"SellerSku\": \"ZID-TEST-12012021\",\n"
                + "            \"ShopSku\": \"D053CAAD4860F4GS-059GBG\",\n"
                + "            \"Name\": \"Shirts Test ZID\",\n"
                + "            \"Variation\": \"One size\",\n"
                + "            \"ParentSku\": \"ZID-TEST-12012021\",\n"
                + "            \"Quantity\": \"2\",\n"
                + "            \"ReservedStock\": \"1\",\n"
                + "            \"Available\": \"1\",\n"
                + "            \"Price\": \"20000.00\",\n"
                + "            \"SalePrice\": \"\",\n"
                + "            \"SaleStartDate\": \"\",\n"
                + "            \"SaleEndDate\": \"\",\n"
                + "            \"Status\": \"active\",\n"
                + "            \"ProductId\": \"\",\n"
                + "            \"Url\": \"https://www.zalora.co.id//Shirts-Test-ZID-2669408.html\",\n"
                + "            \"MainImage\": \"https://static-id.zacdn.com//p/2669408-9936-8049662-1.jpg\",\n"
                + "            \"Images\": {\n"
                + "              \"Image\": \"https://static-id.zacdn.com//p/2669408-9936-8049662-1.jpg\"\n"
                + "            },\n"
                + "            \"Description\": \"test SKU ZID\",\n"
                + "            \"TaxClass\": \"default\",\n"
                + "            \"Brand\": \"Kreasi Nusantara\",\n"
                + "            \"PrimaryCategory\": \"Kemeja Polos\",\n"
                + "            \"PrimaryCategoryId\": \"5714\",\n"
                + "            \"Group\": \"\",\n"
                + "            \"BrowseNodes\": \"\",\n"
                + "            \"ProductData\": {\n"
                + "              \"SkuSupplierConfig\": \"ZID-TEST-12012021\",\n"
                + "              \"SubCatType\": \"Shirts\",\n"
                + "              \"Color\": \"Black\",\n"
                + "              \"ColorFamily\": \"black\",\n"
                + "              \"Gender\": \"Male\",\n"
                + "              \"Sizesystembrand\": \"International\",\n"
                + "              \"IsCoFund\": \"\"\n"
                + "            }\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    }\n"
                + "  }\n"
                + "}";
        JSONObject products = (JSONObject) parser.parse(jsonString);
//        System.out.println(products.toJSONString());
        System.out.println(products.getJSONObject("SuccessResponse").getJSONObject("Body").getJSONObject("Products").getJSONArray("Product").getJSONObject(0).toJSONString());
    }

}
